<a href="https://colab.research.google.com/github/raminass/Software-Project/blob/main/Python_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Review

## Why Python



*   General purpose programming language (script, OOP, interactive)
*   Interpreted (no need of binary, runs until failure)
*   Powerful environment for scientific computing
*   Free - https://www.python.org/downloads/
*   Simple
*   Massive community support

![image.png]()

## Agenda

* Basic Python
* Basic data types (Containers, Lists, Dictionaries, Sets, Tuples)
* Functions
* Classes

## Running modes
1.   Interactivly
  - Starting the Interpreter
  - Executing Python Code (Enter)
  - Exiting the Interpreter(exit())
2.   Running a Python Script from the Command Line
3.   Interacting with Python through an IDE

## Python Versions

We'll be using Python 3 for this iteration of the course. You can check your Python version at the command line by running `python --version`.

In [ ]:
!python3 --version

Python 3.9.16

# Basics of Python

*   Python is a high-level, dynamically typed multiparadigm programming language.
*   Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.
*   Whitespaces are important. Python uses indentation, no braces are needed.


As an example, here is an implementation of the classic quicksort algorithm in Python:

In [ ]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]

## Basic data types

The followings are Built-In data types, next lectures we will see external data structers such Numpy and Pandas.

### Numbers
Every thing is an object in Python

Integers and floats work as you would expect from other languages:

In [ ]:
#32-bit
x = 20
print(x, type(x))

20 <class 'int'>

In [ ]:
x.to_bytes(4,'big')

b'\x00\x00\x00\x14'

In [ ]:
x.bit_length()

Explicit int creation

In [ ]:
x_explicit = int(3) #not common

In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

int object methods

In [ ]:
dir(x)

In [ ]:
x += 1
print(x)
x *= 2
print(x)

21
42

In [ ]:
# 64-bit
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)


Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t))

Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

### Strings

<img src="https://files.realpython.com/media/t.f398a9e25af0.png" width="200" height="70" />

In [ ]:
s = 'foobar'
s[3]

In [ ]:
hello = 'good'   # String literals can use single quotes
world = "morning"   # or double quotes; it does not matter
print(hello, len(hello))

In [ ]:
hw = hello + ' ' + world  # String concatenation
print(hw)

In [ ]:
hw12 = '{}-{}-{}'.format(hello, world, 12)  # string formatting
print(hw12)

In [ ]:
hw22 = f'{hello}-{world}-{22}' # latest way is f-strings
print(hw22)

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace, useful in text processing

You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

### Other bases

In [ ]:
print(0o10) # Octal
print(0x10) # Hexa
print(0b101) # Binary

### Magic Methods
Magic methods in Python are the special methods that start and end with the double underscores. They are also called dunder methods. Magic methods are not meant to be invoked directly by you, but the invocation happens internally from the class on a certain action.

In [ ]:
dir(x)

In [ ]:
x.__pow__(2)

In [ ]:
x **2

## Containers

*   **Python** includes several built-in **container** types: lists, dictionaries, sets, and tuples.  
*   The **Collection** in **Java** is a framework that provides an architecture to store and manipulate the group of objects.

### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2])

is mutatble ?

In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

Lists can be nested.

<img src="https://robocrop.realpython.net/?url=https%3A//files.realpython.com/media/t.08554d94a1e5.png&w=1150&sig=dd460296ea6940e0ea6e809b7d98b1272708da03" width="400" height="210" />

In [ ]:
x = ['a', ['bb', ['ccc', 'ddd'], 'ee', 'ff'], 'g', ['hh', 'ii'], 'j'] # different object types in same list
x

neagitive index

<img src="https://files.realpython.com/media/t.c11ea56e8ca2.png" width="300" height="110" />

In [ ]:
a = ['foo', 'bar', 'baz', 'qux', 'quux', 'corge']
a[-2]

As usual, you can find all the details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

In [ ]:
ynwa = ["you", "will", "never", "walk", "alone"]
ynwa.index("walk") # finding element

### Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f'#{idx+1}: {animal}')

### List comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

List comprehensions can also contain conditions, filter and transform the values in one line:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

<img src="https://files.realpython.com/media/t.b3e3d8f2d100.png" width="300" height="270" />

In [ ]:
# Create a new dictionary with some data
MLB_team = {
     'Colorado' : 'Rockies',
     'Boston'   : 'Red Sox',
     'Minnesota': 'Twins',
     'Milwaukee': 'Brewers',
     'Seattle'  : 'Mariners'
 }

In [ ]:
print(MLB_team['Boston'])       # Get an entry from a dictionary
print('Seattle' in MLB_team)     # Check if a dictionary has a given key

is at mutable ?

In [ ]:
MLB_team['New York'] = 'Mets'    # Set an entry in a dictionary
print(MLB_team['New York'] )

In [ ]:
print(MLB_team['Los Angeles'])  # KeyError

better solution

In [ ]:
print(MLB_team.get('Atlanta', 'N/A'))  # Get an element with a default
print(MLB_team.get('Seattle', 'N/A'))  # Get an element with a default

In [ ]:
del MLB_team['Seattle']        # Remove an element from a dictionary
print(MLB_team.get('Seattle', 'N/A')) # "fish" is no longer a key

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for k, v in d.items():
    print(f'A {k} has {v} legs')

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

Nested Dictionary

In [ ]:
# keys are IDs
students = {
              1: {'name': 'John', 'age': '27', 'sex': 'Male',
                  'address': {'country':'England', 'city':'London'}},
              2: {'name': 'Marie', 'age': '22', 'sex': 'Female',
                  'address': {'country':'France','city':'Lyon'}}
            }

In [ ]:
students[2]['address']['city']

### Sets

Python’s built-in set type has the following characteristics:


*   Sets are unordered
*   Set elements are unique. Duplicate elements are not allowed.
*   A set itself may be modified, but the elements contained in the set must be of an immutable type.

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
x = set(['foo', 'bar', 'baz', 'foo', 'qux', 2, 2, 7])
print(x)

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set
print('fish' in animals)  # prints ?

In [ ]:
animals[0]

In [ ]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))
animals.remove('cat')    # Remove an element from a set
print(len(animals))

_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [ ]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

What will be printed ?
Why ?

In [ ]:
from math import sqrt
print([int(sqrt(x)) for x in range(30)])

Mathimatical view.

<img src="https://files.realpython.com/media/t.ca57b915cec6.png" width="400" height="200" />

In [ ]:
x1 = {'foo', 'bar', 'baz'}
x2 = {'baz', 'qux', 'quux'}
x1.union(x2)

### Tuples

A tuple is an (immutable) ordered list of values.

In [ ]:
tup1 = ('a', 'b', 22, 33)
tup1[2]

try to change it

In [ ]:
tup1[2] = 3

A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)      # Create a tuple
print(d)
print(type(t))
print(d[t])
print(d[(1, 2)])

## Conditional

<img src="https://files.realpython.com/media/t.78f3bacaa261.png" width="400" height="200" />

In [ ]:
if 'foo' in ['bar', 'baz', 'qux', 'foo']:
    print('Expression was true')
    print('Executing statement in suite')
    print('...')
    print('Done.')
print('After conditional')

### The elif Statement

In [ ]:
var = 100
if var == 200:
   print("1 - Got a true expression value")
   print(var)
elif var == 150:
   print("2 - Got a true expression value")
   print(var)
elif var == 100:
   print("3 - Got a true expression value")
   print(var)
else:
   print("4 - Got a false expression value")
   print(var)

print("Good bye!")

## Python Exceptions

A Python program terminates as soon as it encounters an error. In Python, an error can be a **syntax error** or an **exception**.

Syntax errors occur when the parser detects an incorrect statement. Observe the following example:

In [ ]:
print('hello'))

We can use raise to throw an exception if a condition occurs. The statement can be complemented with a custom exception.

In [ ]:
x = 10
if x > 5:
    raise Exception(f'x should not exceed 5. The value of x was: {x}')

Some functions raises exception, in order to handle these exceptions and avoid terminating the program, we can use try/except. demonstrated at class.

## Functions

As every language it comes with Built-In functions, we have encoutered (print(), pow()... )

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

In [ ]:
sign

New PEP 484 function annotations: [read more](https://www.python.org/dev/peps/pep-0484/)

In [ ]:
def sign(x: float) -> str:
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

In [ ]:
sign

We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False, age):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob',age=20)
hello('Fred', loud=True)

# Some Concepts

## Indentation
This is how the code is structured.

Noramally, the standard is four spaces (from the guidelines):

"Python 3 disallows mixing the use of tabs and spaces for indentation."

In [ ]:
a = 0
b = 5
if a < b:
    print("Indentation")

In [ ]:
# IndentationError
if a < b:
print("Indentation")

## Object References


*   Every variable is a reference to an object
*   Upon assignment (=) you are creating a reference for the right-hand side.
*   Object references doesn’t have a single type associated with *them*.

<img src="https://files.realpython.com/media/t.2d7bcb9afaaf.png" width="300" height="100" />

In [ ]:
n = 300
m = n

<img src="https://files.realpython.com/media/t.d368386b8423.png" width="500" height="100" />

In [ ]:
print(id(n))
print(id(m))

In [ ]:
m = 400

<img src="https://files.realpython.com/media/t.d476d91592cd.png" width="500" height="200" />

In Python, every object that is created is given a number that uniquely identifies it. It is guaranteed that no two objects will have the same identifier during any period in which their lifetimes overlap. Once an object’s reference count drops to zero and it is garbage collected,

In [ ]:
print(id(n))
print(id(m))

In [ ]:
m = 'Im string'
print(m)

In [ ]:
spam = [1,2,3]
eggs = spam
eggs.append(99)
spam

In [ ]:
# also function get args by ref
def popit(lst):
    if lst:  # Check if empty
        lst.pop(-1)
popit(spam)
eggs

How to assign by value ?

In [ ]:
list1 = ['dont', 'change', 'me']
list2 = list1.copy()
list2.append('why?')
print(list2)
print(list1)

## Variable Names
Officially, variable names in Python can be any length and can consist of uppercase and lowercase letters (A-Z, a-z), digits (0-9), and the underscore character (_). An additional restriction is that, although a variable name can contain digits, the first character of a variable name cannot be a digit.

## Reserved Words
There is one more restriction on identifier names. The Python language reserves a small set of keywords that designate special language functionality. No object can have the same name as a reserved word.

In [ ]:
help("keywords")

### Importing modules
Calling a .py file from where it can be accessed using the "import" keyword makse it a module

In [ ]:
%%writefile my_module.py

print('Imported my_module...')

test = 'Test String'


def find_index(to_search, target):
    '''Find the index of a value in a sequence'''
    for i, value in enumerate(to_search):
        if value == target:
            return i

    return -1
print(__name__)
if __name__ == "__main__":
    print(2+3)

In [ ]:
import my_module as my
courses = ['History', 'Math', 'Physics', 'CompSci']
my.find_index(courses, 'Math')

# Classes

The syntax for defining classes in Python is straightforward:

In [ ]:
class Employee:

    raise_amt = 1.04

    def __init__(self, first, last, pay):
        self.first = first
        self.last = last
        self.email = first + '.' + last + '@email.com'
        self.pay = pay

    def fullname(self):
        return f'{self.first} {self.last}'

    def apply_raise(self):
        self.pay = int(self.pay * self.raise_amt)



emp_1 = Employee('Lady', 'Gaga', 50000)
emp_2 = Employee('Test', 'Employee', 60000)

print(emp_2.fullname())
print(emp_2.pay)

In [ ]:
print(Employee.raise_amt)

In [ ]:
Employee.raise_amt = 2

In [ ]:
# intsance method
emp_2.apply_raise()
print(emp_2.pay)

## Inheritance

In [ ]:
class Developer(Employee):
    raise_amt = 1.10

    def __init__(self, first, last, pay, prog_lang):
        super().__init__(first, last, pay)
        self.prog_lang = prog_lang


class Manager(Employee):

    def __init__(self, first, last, pay, employees=None):
        super().__init__(first, last, pay)
        if employees is None:
            self.employees = []
        else:
            self.employees = employees

    def add_emp(self, emp):
        if emp not in self.employees:
            self.employees.append(emp)

    def remove_emp(self, emp):
        if emp in self.employees:
            self.employees.remove(emp)

    def print_emps(self):
        for emp in self.employees:
            print('-->', emp.fullname())


dev_1 = Developer('Corey', 'Schafer', 50000, 'Python')
dev_2 = Developer('Test', 'Employee', 60000, 'Java')

mgr_1 = Manager('Sue', 'Smith', 90000, [dev_1])

print(mgr_1.email)

mgr_1.add_emp(dev_2)
mgr_1.remove_emp(dev_2)

mgr_1.print_emps()